title: "Gab-Dev-7 Dotfiles"
description: "A high-performance Arch Linux + Hyprland environment."
baseurl: "/dotfiles"
url: "https://gab-dev-7.github.io"
markdown: kramdown
permalink: /:title/
exclude: ["README.md", "LICENSE", "install.sh"]
theme: null
