title: "Gab-Dev-7 Dotfiles"
description: "A high-performance Arch Linux + Hyprland environment."
baseurl: "/dotfiles" # keep empty for custom domain or user site
url: "https://gab-dev-7.github.io"
markdown: kramdown
permalink: /:title/
